# Bitnami Elasticsearch — helm install ebooks-elasticsearch bitnami/elasticsearch -f elasticsearch-values.yaml -n ebooks-infra
master:
  replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

data:
  replicaCount: 0  # single-node para MVP

coordinating:
  replicaCount: 0

security:
  enabled: false

sysctlImage:
  enabled: true
