image:
  repository: ghcr.io/change-me/ebooks-partner-service
  tag: latest
service:
  port: 3005
health:
  path: /health
  initialDelaySeconds: 20
resources:
  requests:
    memory: "192Mi"
    cpu: "100m"
  limits:
    memory: "384Mi"
    cpu: "400m"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
env:
  RABBITMQ_URL: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@ebooks-rabbitmq.ebooks-infra.svc.cluster.local:5672"
secretEnv:
  - name: DATABASE_URL
    secretKey: DATABASE_URL_PARTNER
  - name: RABBITMQ_USER
    secretKey: RABBITMQ_USER
  - name: RABBITMQ_PASSWORD
    secretKey: RABBITMQ_PASSWORD
