apiVersion: v1
kind: Namespace
metadata:
  name: ebooks
  labels:
    app.kubernetes.io/managed-by: helm
---
apiVersion: v1
kind: Namespace
metadata:
  name: ebooks-infra
  labels:
    app.kubernetes.io/managed-by: helm
